export const Strings = {
  // O1 Welcome
  o1Headline: 'Your money.\nFinally clear.',
  o1Subtext: 'Track everything. Plan with confidence.\nNo bank access needed.',
  o1Cta: 'Get Started',
  o1SignIn: 'Already set up? Sign in',

  // O2 Currency
  o2Title: 'Base Currency',
  o2Heading: 'Choose your currency',
  o2Subtitle: 'Used for all net worth and budget calculations.',
  o2Cta: 'Continue',
  o2NoteLabel: 'Note:',
  o2NoteBody: ' This is your reporting currency. Individual accounts can still be in any currency.',
  currencyEGP: 'Egyptian Pound',
  currencyUSD: 'US Dollar',
  currencyEGPCode: 'EGP',
  currencyUSDCode: 'USD',

  // O3 Security
  o3Title: 'Security',
  o3HeaderTitle: 'Protect your data',
  o3HeaderSub: 'Stays on your device only.',
  o3PinLabel: 'Set PIN',
  o3PinSub: '4 or 6 digit code',
  o3BiometricLabel: 'Biometric',
  o3BiometricSub: 'Face ID or fingerprint',
  o3SkipLabel: 'Skip for now',
  o3SkipSub: 'Enable later in Settings',
  o3BestBadge: 'Best',
  o3Cta: 'Continue',

  // O4 Add Account
  o4Title: 'Add Account',
  o4Subtitle: 'Start by adding one account — you can add more next.',
  o4SectionType: 'ACCOUNT TYPE',
  o4SectionName: 'ACCOUNT NAME',
  o4SectionCurrency: 'CURRENCY',
  o4SectionBalance: 'BALANCE',
  o4SectionColor: 'COLOR — 12 PRESETS',
  o4SectionRevolving: 'REVOLVING BALANCE',
  o4SectionLimit: 'CREDIT LIMIT',
  o4SectionMinPayment: 'MIN. PAYMENT',
  o4SectionDueDay: 'DUE DAY',
  o4SectionApr: 'APR (%)',
  o4NameLabel: 'Account Name',
  o4NamePlaceholder: 'e.g. CIB Savings',
  o4BalanceLabel: 'Opening Balance',
  o4BalancePlaceholder: '0',
  o4ColorLabel: 'Color',
  o4CreditLimitLabel: 'Credit Limit',
  o4CreditLimitPlaceholder: '0',
  o4RevolvingLabel: 'Revolving Balance',
  o4RevolvingPlaceholder: '0',
  o4MinPaymentLabel: 'Minimum Payment',
  o4MinPaymentPlaceholder: '0',
  o4DueDayLabel: 'Statement Due Day',
  o4DueDayPlaceholder: 'e.g. 15',
  o4InterestLabel: 'Track Interest',
  o4InterestOn: 'ON',
  o4InterestOff: 'OFF',
  o4AprLabel: 'Annual Percentage Rate (APR %)',
  o4AprPlaceholder: 'e.g. 2.99',
  o4Cta: 'Save Account',

  // O4 validation errors
  errNameRequired: 'Account name is required',
  errNameTooLong: 'Name must be 30 characters or less',
  errNameDuplicate: 'This name is already used',
  errBalanceInvalid: 'Please enter a valid amount',
  errCreditLimitRequired: 'Credit limit is required for credit cards',
  errAprRequired: "Please enter your card's APR",

  // Generic Zod error map fallbacks
  errRequired: 'This field is required',
  errTooShort: 'Too short',
  errTooLong: 'Too long',
  errInvalid: 'Invalid value',

  // Account types
  typeBank: 'Bank',
  typeSmartWallet: 'Smart Wallet',
  typePhysicalWallet: 'Phys. Wallet',
  typePhysicalSavings: 'Savings',
  typeCreditCard: 'Credit Card',

  // O5 More Accounts
  o5Title: 'Your Accounts',
  o5Subtitle: 'Got other accounts? Add them now — or skip and do it later.',
  o5SubtitleSuffix: ' added. Add more or continue.',
  o5AddAnother: 'Add another account',
  o5SettingsHint: 'You can always add more from Settings',
  o5Cta: "I'm done",

  // O6 Ready
  o6Title: "You're all set!",
  o6Subtitle: "Your MoneyApp is configured. Here's your summary.",
  o6Cta: 'Open My Dashboard',
  o6Currency: 'Base Currency',
  o6Security: 'Security',
  o6Accounts: 'Accounts',
  o6TotalBalance: 'Total Balance',
  o6SecurityPin: 'PIN Code',
  o6SecurityBiometric: 'Biometrics',
  o6SecurityEnabled: 'Enabled',
  o6SecuritySkipped: 'Not set',
  o6AccountsUnit: 'accounts',

  // Placeholder dashboard
  placeholderTitle: 'Dashboard coming soon',
  placeholderSubtitle: 'M1 complete — M1.5 next.',

  // Dashboard (U2)
  // Account card info rows
  cardLimitLabel: 'Limit',
  cardAvailableLabel: 'Available',
  cardMinPayLabel: 'Min Pay',
  cardOverLimit: 'Over Limit',
  cardTypeLabel: 'Type',
  cardCurrencyLabel: 'Currency',
  cardOpeningLabel: 'Opening',

  dashAddPrefix: 'Add',
  dashAvailableToSpend: 'Available to Spend',
  dashNetWorthTitle: 'Net Worth',
  dashAssetsLabel: 'Assets',
  dashLiabilitiesLabel: 'Liabilities',
  dashMonthSpentTitle: 'Spent This Month',
  dashSeeAll: 'See all',

  // Account Detail (U3)
  accountDetailEdit: 'Edit',
  accountDetailSave: 'Save',
  accountDetailCancel: 'Cancel',
  accountDetailMore: 'More',
  accountDetailBalance: 'Current Balance',
  accountDetailAdjustBalance: 'Adjust Balance',
  accountDetailArchive: 'Archive',
  accountDetailArchiveTitle: 'Archive Account?',
  accountDetailArchiveBody: 'This account will be hidden from your dashboard and all calculations.',
  accountDetailArchiveCCWarning: 'Outstanding credit card balance will still affect net worth.',
  accountDetailArchiveConfirm: 'Archive',

  // Add Account screen (U4 — main app)
  u4Title: 'Add Account',
  u4Cta: 'Save Account',

  // Adjust Balance sheet
  adjustBalanceTitle: 'Adjust Balance',
  adjustBalanceLabel: 'New Balance',
  adjustBalanceSave: 'Save Balance',
  adjustBalanceCancel: 'Cancel',

  // Settings Main (U23)
  settingsTitle: 'Settings',
  settingsCurrencyRow: 'Currency',
  settingsCurrencyDesc: 'USD / EGP exchange rate',

  // Settings Currency (U26)
  currencyScreenTitle: 'Currency',
  currencyRateLabel: 'Exchange Rate',
  currencyRateSub: 'EGP per 1 USD',
  currencyLastFetched: 'Last updated',
  currencyNeverFetched: 'Never fetched',
  currencyManualLabel: 'Manual Override',
  currencyManualSub: 'Set your own rate',
  currencyFetchCta: 'Refresh Rate',
  currencySaveCta: 'Save Rate',

  // Empty States
  emptyAccountsTitle: 'No accounts yet',
  emptyAccountsSub: 'Add your first account to get started.',
  emptyAccountsCta: 'Add Account',
  emptyTransactionsTitle: 'No transactions yet',
  emptyTransactionsSub: 'Transactions will appear here.',
  emptyBillsTitle: 'No bills yet',
  emptyBillsSub: 'Bills will appear here.',
  emptyGoalsTitle: 'No goals set',
  emptyGoalsSub: 'Goals will appear here.',
  emptyBudgetTitle: 'No budget set',
  emptyBudgetSub: 'Your budget will appear here.',

  // U25 Settings Categories
  categoriesTitle: 'Categories',
  categoriesTabExpense: 'Expense',
  categoriesTabIncome: 'Income',
  categoriesDefaultSection: 'DEFAULTS',
  categoriesCustomSection: 'CUSTOM',
  categoriesAddBtn: 'Add Category',
  categoriesLimitMsg: 'Maximum 30 custom categories reached',
  categoriesAddSheetTitle: 'New Category',
  categoriesEditSheetTitle: 'Edit Category',
  categoriesNameLabel: 'Name',
  categoriesNamePlaceholder: 'e.g. Travel',
  categoriesTypeLabel: 'TYPE',
  categoriesIconLabel: 'ICON',
  categoriesColorLabel: 'COLOR',
  categoriesSaveCta: 'Save',
  categoriesErrNameRequired: 'Category name is required',
  categoriesErrNameTooLong: 'Name must be 20 characters or less',
  categoriesErrNameDuplicate: 'This name is already used',
  categoriesErrIconRequired: 'Please select an icon',
  categoriesDeleteTitle: 'Delete Category',
  categoriesDeleteBody: (name: string) => `Delete "${name}"? This cannot be undone.`,
  categoriesDeleteConfirm: 'Delete',
  categoriesDeleteCancel: 'Cancel',
  categoriesReassignTitle: (name: string) => `"${name}" has transactions`,
  categoriesReassignBody: 'Move its transactions to:',
  categoriesReassignConfirm: 'Move & Delete',

  // U23 Settings rows (categories row)
  settingsCategoriesRow: 'Categories',
  settingsCategoriesDesc: 'Manage expense and income categories',

  // U6 Add Transaction sheet
  addTxTitle: 'Add Transaction',
  addTxTypeExpense: 'Expense',
  addTxTypeIncome: 'Income',
  addTxTypeTransfer: 'Transfer',
  addTxTypeCCPayment: 'CC Payment',
  addTxAccountLabel: 'Account',
  addTxFromLabel: 'From',
  addTxToLabel: 'To',
  addTxCategoryLabel: 'Category',
  addTxDateLabel: 'Date',
  addTxNoteLabel: 'Note',
  addTxNotePlaceholder: 'Add a note (optional)',
  addTxRateLabel: 'Rate',
  addTxRateSubGlobal: 'EGP per 1 USD · global rate',
  addTxRateSubCustom: 'EGP per 1 USD · custom rate',
  addTxRateOverrideLabel: 'Override',
  addTxSaveCta: 'Save',
  addTxErrAmountRequired: 'Enter an amount',
  addTxErrAmountZero: 'Amount must be greater than 0',
  addTxErrAccountRequired: 'Select an account',
  addTxErrFromRequired: 'Select source account',
  addTxErrToRequired: 'Select destination account',
  addTxErrSameAccount: 'From and To must be different accounts',
  addTxErrCategoryRequired: 'Select a category',
  addTxErrCcPaymentSourceMustBeAsset: 'Pay from an asset account',
  addTxErrCcPaymentTargetMustBeCC: 'Pay to a credit card account',
  addTxErrTransferNoCc: 'Use Credit Pay for credit card moves',
  addTxErrRateRequired: 'Enter the exchange rate',
  addTxErrRateInvalid: 'Rate must be greater than 0',
  addTxInsufficientBalance: (name: string) => `Insufficient balance in ${name}`,
  addTxPickAccountTitle: 'Select Account',
  addTxPickFromTitle: 'From Account',
  addTxPickToTitle: 'To Account',
  addTxPickCategoryTitle: 'Select Category',

  // U5 Transaction List
  transactions: 'Transactions',
  searchTransactionsPlaceholder: 'Search transactions…',
  filterAll: 'All',
  filterExpense: 'Expense',
  filterIncome: 'Income',
  filterTransfer: 'Transfer',
  filterCcPayment: 'Credit Pay',
  transferTitle: 'Transfer',
  ccPaymentTitle: 'Credit Card Payment',
  unknownAccount: 'Unknown account',
  uncategorized: 'Uncategorized',
  noResultsHeadline: 'No transactions found',
  noResultsSubtext: 'Try a different search term or filter.',
  todayLabel: 'TODAY',
  yesterdayLabel: 'YESTERDAY',

  // U7 Transaction Detail
  detailHeader: 'Transaction',
  detailCategory: 'CATEGORY',
  detailAccount: 'ACCOUNT',
  detailDateTime: 'DATE & TIME',
  detailOriginalAmount: 'ORIGINAL AMOUNT',
  detailExchangeRate: 'EXCHANGE RATE',
  detailNote: 'NOTE',
  detailNoteEmpty: 'No note',
  capturedBadge: 'Captured',
  editTransaction: 'Edit Transaction',
  editTxTitle: 'Edit Transaction',
  deleteTransaction: 'Delete',
  deleteConfirmTitle: 'Delete this transaction?',
  deleteConfirmBody: 'The account balance will be restored. This cannot be undone.',
  deleteCancel: 'Cancel',
  detailNotFoundHeadline: 'Transaction not found',
  detailNotFoundCta: 'Back to transactions',
  errDeleteFailed: 'Could not delete transaction. Please try again.',
  typeBadgeExpense: 'Expense',
  typeBadgeIncome: 'Income',
  typeBadgeTransfer: 'Transfer',
  typeBadgeCcPayment: 'CC Payment',

  // U31 Advanced Filter Drawer
  filterTitle: 'Filters',
  filterReset: 'Reset',
  filterApply: 'Apply',
  filterApplyWithCount: (n: number) => `Apply (${n})`,

  filterSectionAccounts: 'Accounts',
  filterSectionCategories: 'Categories',
  filterSectionDate: 'Date',
  filterSectionAmount: 'Amount',

  filterAllAccounts: 'All accounts',
  filterAllCategories: 'All categories',

  datePresetToday: 'Today',
  datePresetThisWeek: 'This week',
  datePresetThisMonth: 'This month',
  datePresetLastMonth: 'Last month',
  datePresetLast30Days: 'Last 30 days',
  datePresetThisYear: 'This year',
  datePresetAllTime: 'All time',
  datePresetCustom: 'Custom...',
  filterCustomDateRangeTitle: 'Custom date range',
  filterCustomFromLabel: 'From',
  filterCustomToLabel: 'To',

  filterPickAccountsTitle: 'Select Accounts',
  filterPickCategoriesTitle: 'Select Categories',
  filterPickerDone: 'Done',

  filterAmountFromPlaceholder: 'Min',
  filterAmountToPlaceholder: 'Max',

  filterCategoryTypeExpense: 'Expense',
  filterCategoryTypeIncome: 'Income',
} as const;
