/**
 * Emits the Cairo Nights design tokens as a self-contained CSS block for HTML
 * mockups, read live from global.css and constants/theme.ts.
 *
 * A mockup built on this cannot drift from the app: the colours are the same
 * variables the app renders with, and the sizes are the same numbers, at the
 * 390pt base width the tokens are authored against (ms() is identity there).
 *
 *   node scripts/design-tokens.js          # or: npm run design:tokens
 *   node scripts/design-tokens.js > /tmp/tokens.css
 */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

function readColors() {
  const css = fs.readFileSync(path.join(root, 'global.css'), 'utf8');
  // The app is dark-only; the light variant duplicates dark. Take dark as the source.
  const dark = /@variant dark \{([\s\S]*?)\n {2}\}/.exec(css);
  if (!dark) throw new Error('global.css: could not find the @variant dark block');
  const vars = [...dark[1].matchAll(/^\s*(--[a-z0-9-]+):\s*([^;]+);/gm)].map((m) => [
    m[1],
    m[2].trim(),
  ]);

  // The gold gradient stops live in @theme inline as literals, not in the dark
  // variant — without them a mockup would have to hand-write the brand hex.
  const theme = /@theme inline \{([\s\S]*?)\n\}/.exec(css);
  if (theme) {
    for (const m of theme[1].matchAll(/^\s*(--color-[a-z0-9-]+):\s*(#[0-9a-fA-F]{3,8})\s*;/gm)) {
      vars.push([m[1], m[2]]);
    }
  }
  return vars;
}

// Token values are authored as ms(n) / msFont(n) and scale at runtime. At the
// 390pt base width the scale factor is 1, so the literal is the mockup value.
function readNumericGroup(source, name) {
  const block = new RegExp(`export const ${name} = \\{([\\s\\S]*?)\\n\\} as const`).exec(source);
  if (!block) return [];
  return [
    ...block[1].matchAll(/^\s*([A-Za-z][A-Za-z0-9]*):\s*(?:ms|msFont)\((\d+(?:\.\d+)?)\)/gm),
  ].map((m) => [m[1], m[2]]);
}

// Colors.shared and AcctTokens are nested objects of hex literals, so neither
// readColors (global.css) nor readNumericGroup (ms()/msFont()) can see them.
// Without these a mockup has to hand-copy the brand gradient stops and all 32
// account swatches — which is exactly what the round-4 mockup had to do.
function readSharedColors(source) {
  const block = /\n {2}shared: \{([\s\S]*?)\n {2}\},/.exec(source);
  if (!block) throw new Error('theme.ts: could not find the Colors.shared block');
  return [...block[1].matchAll(/^\s*([A-Za-z][A-Za-z0-9]*):\s*'(#[0-9a-fA-F]{3,8})'/gm)].map(
    (m) => [m[1], m[2]],
  );
}

function readAcctTokens(source) {
  const block = /export const AcctTokens = \{([\s\S]*?)\n\} as const/.exec(source);
  if (!block) throw new Error('theme_tokens.ts: could not find the AcctTokens block');
  const families = [
    ...block[1].matchAll(
      /^\s*([A-Za-z][A-Za-z0-9]*):\s*\{\s*rich:\s*'(#[0-9a-fA-F]{6})',\s*soft:\s*'(#[0-9a-fA-F]{6})'\s*\}/gm,
    ),
  ].map((m) => [m[1], m[2], m[3]]);
  if (!families.length) throw new Error('theme_tokens.ts: AcctTokens parsed to zero families');
  return families;
}

const theme = fs.readFileSync(path.join(root, 'src/constants/theme.ts'), 'utf8');
const themeTokens = fs.readFileSync(path.join(root, 'src/constants/theme_tokens.ts'), 'utf8');

const kebab = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .toLowerCase();

const out = [];
out.push('<style>');
out.push('/* Cairo Nights tokens — generated by scripts/design-tokens.js. Do not hand-edit. */');
out.push(':root {');

for (const [name, value] of readColors()) {
  out.push(`  ${name}: ${value};`);
}

out.push('');
for (const [group, prefix] of [
  ['Type', 'type'],
  ['Radius', 'radius'],
  ['Spacing', 'space'],
  ['Size', 'size'],
]) {
  for (const [name, value] of readNumericGroup(theme, group)) {
    out.push(`  --${prefix}-${kebab(name)}: ${value}px;`);
  }
}

out.push('');
out.push('  /* constants/theme.ts -> Colors.shared */');
for (const [name, value] of readSharedColors(theme)) {
  out.push(`  --${kebab(name)}: ${value};`);
}

out.push('');
out.push('  /* constants/theme_tokens.ts -> AcctTokens: 16 families x rich/soft */');
for (const [family, rich, soft] of readAcctTokens(themeTokens)) {
  out.push(`  --acct-${kebab(family)}-r: ${rich};`);
  out.push(`  --acct-${kebab(family)}-s: ${soft};`);
}

out.push('');
out.push('  /* Sora = numbers, headings, CTAs. Inter = body, labels. */');
out.push("  --font-display: 'Sora', 'Avenir Next', 'Segoe UI', system-ui, sans-serif;");
out.push("  --font-body: 'Inter', 'Helvetica Neue', system-ui, sans-serif;");
out.push('}');
out.push('');
out.push('/* Device frame: tokens are authored at the 390pt base width. */');
out.push('.device {');
out.push('  width: 390px; min-height: 844px; margin: 0 auto;');
out.push('  background: var(--background); color: var(--foreground);');
out.push('  font-family: var(--font-body); overflow: hidden;');
out.push('}');
out.push('</style>');

console.log(out.join('\n'));
