/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/add_account` | `/add_account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/currency` | `/currency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/more_accounts` | `/more_accounts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/ready` | `/ready`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/security` | `/security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/add_account` | `/add_account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/currency` | `/currency`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/more_accounts` | `/more_accounts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/ready` | `/ready`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/security` | `/security`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/add_account${`?${string}` | `#${string}` | ''}` | `/add_account${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/currency${`?${string}` | `#${string}` | ''}` | `/currency${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/more_accounts${`?${string}` | `#${string}` | ''}` | `/more_accounts${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/ready${`?${string}` | `#${string}` | ''}` | `/ready${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/security${`?${string}` | `#${string}` | ''}` | `/security${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/add_account` | `/add_account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/currency` | `/currency`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/more_accounts` | `/more_accounts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/ready` | `/ready`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/security` | `/security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; };
    }
  }
}
